### ISSUE TITLE
Samsung 980 pro m.2 not beeing detected

### ISSUE THREAD

**Issue by muniategui** [ashaduri/gsmartcontrol#1]
As the tittle says the ssd is not beeing detected, i don't know if the model has to be added to the database or is due to beeing and m.2 since the sata ssd is beeing detected perfectly.

Thanks

**Comment by ashaduri** [comment]
As per documentation, "GSmartControl supports ATA drives (both PATA and SATA), various USB to ATA bridges and drives behind some RAID controllers".
NVMe drives are not supported (yet).

**Comment by ashaduri** [comment]
Duplicate of #4

**Comment by antdude** [comment]
Ah, that's why I can't view my new WD Black SN750 1TB with Heatsink (WDS100T3XHC) M.2 NVMe Interface PCIe 3.0 x4 Internal Solid State Drive (SSD) with 3D TLC NAND 2280 in my new 64-bit W10 Pro PC. :(
