### ISSUE TITLE
Crash on Windows 10 21H1

### ISSUE THREAD

**Issue by ashaduri** [ashaduri/gsmartcontrol#16]
Reported by email:

It appears that GSmartControl 1.1.3 crashes on Windows 10 21H1.

The program starts just fine and scans the drives, then it crashes when 
I double-click on a drive to see details.

Tried debugging in Visual Studio and it appears that the problem is an 
assertion in some GTK library, but it's hard to be sure without symbols.

Running "smartctl" from the command line works without problems, I can 
scan for drives and print SMART data.

Tried both the win64 and win32 versions.

Downgraded to version 1.1.2 -> same problem.
Downgraded to version 1.0.2 -> it works!

**Comment by ashaduri** [comment]
Hi,
Unfortunately, I could not reproduce it on my Windows 10 21H1.

Could you please check if the problem is still present?

I would also like to know your language settings in Windows (are you using a localized version of Windows?).

Also, please attach "smartctl -x ..." output, maybe the bug is specific to that output.

Thanks!

**Comment by larsen0815** [comment]
Same problem here on Windows 10 22H2 (German) and gsmartcontrol 1.1.3. Installed in "C:\Program Files\GSmartControl"

Fixed with gsmartcontrol 1.1.4 =)

**Comment by ashaduri** [comment]
I'm going to close this issue since there's been no follow-up for a while, and it seems that 1.1.4 does not have this problem.
