### ISSUE TITLE
Hitachi HUA72202's all report MAX_INT "Mechanical Start Failures"

### ISSUE THREAD

**Issue by DrivebyCoding** [ashaduri/gsmartcontrol#19]
The Hitachi HUA72202's with Dell FW JKAOA3HA I've tested (6 as of now) all show "Number of Mechanical Start Failures" under Statistics as 4294967295. I assume this is some sort of firmware deficiency, but reporting in case you maintain a quirks table.

How do you get this statistic from smartctl? It's not part of the ones reported by a regular "smartvtl -a"

GSmartControl version: 1.1.3 from Ubuntu 20.04.3

**Comment by ashaduri** [comment]
Probably either the value is not interpreted correctly by smartctl, or indeed a firmware deficiency. The smartmontools developers may be interested in this.

The current practice is to use `smartctl -x` by default, it gets more information than `-a`.
