### ISSUE TITLE
update-smart-drivedb.exe Win64 v.1.1.4, portable | End of the progression bar not reached by the progression element

### ISSUE THREAD

**Issue by Ricky-Tigg** [ashaduri/gsmartcontrol#34]
**OS:** Windows | **edition:** 11; **version:** 21H2. **update-smart-drivedb.exe Win64 version:** 1.1.4, as portable.

Hello. **End of the progression bar** not reached by the **progression element** despite the process covering the current task is as **completed** state.

![update-smart-drivedb exe_execution](https://user-images.githubusercontent.com/26058215/169023003-8ee1386a-1472-4282-a5d4-9573cd25a03d.png)

**Comment by ashaduri** [comment]
Thanks for the report.

This is a (harmless) issue in [smartmontools](https://www.smartmontools.org), which `update-smart-drivedb` is part of. You can file the issue with smartmontools.
