### ISSUE TITLE
Mounted partitions of USB external mass storage devices, reported as "not mounted"

### ISSUE THREAD

**Issue by Ricky-Tigg** [ashaduri/gsmartcontrol#35]
**OS:** Windows | **edition:** 11; **version:** 21H2. **gsmartcontrol.exe Win64 version:** 1.1.4, as portable.

Hello. Partitions of USB external mass storage devices being reported in _Windows_' _File Explorer_ as mounted and therefore whose content on them is being accessible, are reported as being **not mounted** by this application.

![gsmartcontrol exe_non-SMART_device](https://user-images.githubusercontent.com/26058215/169029591-bc6c8ce1-dd02-462d-8873-54254d656a73.png)

**Comment by ashaduri** [comment]
Thanks a lot for the report,

Should be fixed in https://github.com/ashaduri/gsmartcontrol/commit/5435feb9329cef60c6e06dee7855fba645956bd5
