### ISSUE TITLE
Software open then crash:

### ISSUE THREAD

**Issue by ToothedTomb** [ashaduri/gsmartcontrol#37]
This is the error that I have got:
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
<error> [gtk] posix_spawn avoided (workdir specified) (fd close requested) 
<error> [gtk] setenv()/putenv() are not thread-safe and should not be used after threads are created
Segmentation fault

Dont know what it means but might be a bug in the code.
Thanks Jonathan

**Comment by ashaduri** [comment]
Please describe the circumstances of the bug, gsmartcontrol version, operating system, etc...

**Comment by ToothedTomb** [comment]
Hi i am running Linux Mint 20.3 and installed from the software center. I got GSmartControl version 1.1.3.
Thanks.

**Comment by ToothedTomb** [comment]
Hi I fixed the problem by installing the 1.1.4 version. Thanks.
