### ISSUE TITLE
Update Drive Database Error

### ISSUE THREAD

**Issue by boxerfan88** [ashaduri/gsmartcontrol#42]
**Version and Environment**
 - GSmartControl version: 1.1.4
 - OS: Windows 10

**Describe the Bug**
When trying to execute Update Drive Database, it will throw an error "Failed to execute child process (Bad file descriptor)".
I can successfully execute update-smart-drivedb.exe from the program folder.

**To Reproduce**
1. Go to 'Options'
2. Click on 'Update Drive Database'
3. See error

**Screenshots**

<img width="281" alt="2023-03-19 07_48_45-GSmartControl" src="https://user-images.githubusercontent.com/23348797/226146109-87a94a64-ef41-4ab8-ae0c-e59970ca2845.png">

**Additional Context**
I have tried uninstalling & reinstalling GSmartControl, the problem remains.

**Comment by HubKing** [comment]
There is no "Discussion" tab, so I have to ask here.  On Linux, it update fails if `xterm` does not exist. Since I use another, better terminal app, I had uninstalled xterm. Is the xterm an important part of the Linux, like VI, that all systems are supposed to have? Otherwise, can't GSmartControl use any available terminal app or ... I don't know, does it really need a terminal app to update the database?

![image](https://github.com/ashaduri/gsmartcontrol/assets/10900489/86545577-fb0f-41fa-a624-8452c10ce7a7)

**Comment by ashaduri** [comment]
> There is no "Discussion" tab, so I have to ask here. On Linux, it update fails if `xterm` does not exist. Since I use another, better terminal app, I had uninstalled xterm. Is the xterm an important part of the Linux, like VI, that all systems are supposed to have? Otherwise, can't GSmartControl use any available terminal app or ... I don't know, does it really need a terminal app to update the database?
> 
> ![image](https://user-images.githubusercontent.com/10900489/252800076-86545577-fb0f-41fa-a624-8452c10ce7a7.png)

Yes, it needs xterm. If you installed a GSmartControl package, it should have included xterm as its dependency. If not, please file a bug report against that package. The xterm package on my distribution is 38K, so you won't gain much by uninstalling it.
The reason that only xterm is supported is two-fold:
- Some terminal apps have different command invocation syntax.
- The default terminal app selection mechanism is desktop-specific, while GSmartControl aims to be very cross-platform.

On the other hand, wayland-based desktops are getting stable, so another mechanism will have to be implemented soon-ish.

**Comment by ashaduri** [comment]
Fixed on Windows in git main branch.
