### ISSUE TITLE
Unknown device

### ISSUE THREAD

**Issue by antonio-petricca** [ashaduri/gsmartcontrol#43]
**Version and Environment**

 - GSmartControl version: 1.1.4
 - OS: Ubuntu 22.04.2

**Issue description**

I am running your excellent software on a Dell Precision 7560 equipped with 2 NVME SSD, where both are Western Digital.

Unfortunately I get an "Unknown model" for them without any detail.

I attach the `gsmartcontrol-root -v` output to allow you to investigate.

[gsmartcontrol-root.log](https://github.com/ashaduri/gsmartcontrol/files/11232253/gsmartcontrol-root.log)

**Comment by ashaduri** [comment]
Duplicate of #4
