### ISSUE TITLE
Fatal error, cannot create UI-resource widgets

### ISSUE THREAD

**Issue by dacorsa** [ashaduri/gsmartcontrol#45]
When i run GSC on my ubuntu lunar, i see this error:

![immagine](https://github.com/ashaduri/gsmartcontrol/assets/36949692/8a33603e-a71a-4b6b-a5cc-89c5a8d2e154)

Can you help me to solve it?

Best regards

**Comment by ashaduri** [comment]
Hi,

Which version? Are you compiling, using an official repository, or?

**Comment by dacorsa** [comment]
i have compiled this repository
the official works but ask to set smartctl in preferences

**Comment by ashaduri** [comment]
Please use the official version.
If smartctl is not available on your system, please install "smartmontools" package.
