### ISSUE TITLE
Ability to display current disk temperature in the drive list

### ISSUE THREAD

**Issue by HubKing** [ashaduri/gsmartcontrol#49]
**Version and Environment**
 - GSmartControl version: [Are you using the latest released version or git?] 1.1.4, Arch
 - OS: [e.g. openSUSE Linux 15.4] Manjaro

**Is your feature request related to a problem? Please describe.**
I have multiple WD USB disks. Gnome Disks can't show Smart data for them, but GsmartControl can. But to check the current temperature, which I think is important to monitor in real time to prevent overheating, I have to open the disk and click the temperature tab, which is tedious.

**Describe the solution you'd like**
Option to display current temperature data below the disk icons.

**Describe alternatives you've considered**
None.

**Additional context**
For example, Crystal Disk Info allows users to see the current temperatures of multiple disks at once.

![image](https://github.com/ashaduri/gsmartcontrol/assets/10900489/4fad45be-9b97-4e28-9d5b-13c3bddfed45)

**Comment by ashaduri** [comment]
Hi,
The way it works is that you would have to refresh the drive list each time to see the updated temperature.
Please keep in mind that GSmartControl is not a monitoring application and I'm not sure that displaying a potentially outdated info is good UX.
I would suggest using a different application which does real-time monitoring, and using GSmartControl to check the SMART data occasionally.
