### ISSUE TITLE
Include Start Time of Scan Test in Smartctl Output

### ISSUE THREAD

**Issue by wind77** [ashaduri/gsmartcontrol#51]
**Version and Environment**
 - GSmartControl version: 1.1.4
 - OS: Manjaro (Kernel 6.4.9.1)

**Is your feature request related to a problem? Please describe.**
I'm new to GSmartControl - previously using Gnome Disks.
I like GSmartControl being able to scan multiple disks simultaneously, which really saves my time.
However, similar to Gnome Disks, GSmartControl does not record Start Time of scan in the Smartctl Output.
The relevant section of Smartctl Output only shows:

> ATA Version is:   ACS-2 (minor revision not indicated)
> SATA Version is:  SATA 3.0, 6.0 Gb/s (current: 6.0 Gb/s)
> **Local Time is:    Thu Aug 17 22:10:18 2023 +08**
> SMART support is: Available - device has SMART capability.
> SMART support is: Enabled

And I believe the "Local Time" refers to the Completion Time of the scan?
There is no place I can find any reference to the Start Time of the test.

**Describe the solution you'd like**
In Device Information > Self Test > Estimated duration, GSmartControl does provide an estimate of the time required to run various tests.
However, this is only an estimate, and not actual.
It would be more useful to include the Start Time and End Time of the test, so that users can have more precise control over the disk management.

Also, it would be useful to keep the Smartctl Output separate from SMART test, which run at app startup, and it will override the Smartctl Output of the previous test.

Thanks.

**Comment by ashaduri** [comment]
> However, similar to Gnome Disks, GSmartControl does not record Start Time of scan in the Smartctl Output

SMART data comes from the drive firmware, so no one can really record anything in there. Smartctl can only read what the drive gives it, which is the start time in "power on hours" unit, the total number of hours of drive had power.

> And I believe the "Local Time" refers to the Completion Time of the scan?

Local Time in smartctl output is the OS time when smartctl command was run.

> However, this is only an estimate, and not actual.

Again, this is supplied by the drive firmware and is often quite off. The test is performed by the drive itself and the duration greatly depends on the number of errors, OS access, etc...

> Also, it would be useful to keep the Smartctl Output separate from SMART test, which run at app startup, and it will override the Smartctl Output of the previous test.

I think there is a misunderstanding here. SMART self-tests are never run on application startup. What you see there is simply what the drive reports to smartctl.
