### ISSUE TITLE
Can't get SMART Values on MacOS

### ISSUE THREAD

**Issue by toomanyairmiles** [ashaduri/gsmartcontrol#54]
**Version and Environment**
 - GSmartControl version: Freshly installed today on freshly installed homebrew
 - OS: Mac OS Ventura 13.5 (22G74)

**Describe the Bug**
On launch
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Model Number"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "PCI Vendor/Subsystem ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "IEEE OUI Identifier"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Controller ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "NVMe Version"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Number of Namespaces"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Firmware Updates (0x02)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional Admin Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional NVM Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Maximum Data Transfer Size"
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section(): Unknown section encountered.
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Model Number"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "PCI Vendor/Subsystem ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "IEEE OUI Identifier"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Controller ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "NVMe Version"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Number of Namespaces"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Firmware Updates (0x02)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional Admin Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional NVM Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Maximum Data Transfer Size"
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section(): Unknown section encountered.
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<warn>  [app] SmartctlParser::parse_full(): No ATA sections could be parsed. Returning.
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<warn>  [app] SmartctlParser::parse_full(): No ATA sections could be parsed. Returning.
<warn>  [hz] FS warning: Unable to check if a path "/Users/anthonynm/.config/gsmartcontrol/gsmartcontrol.conf" points to directory: No such file or directory.
FOOLON-ContractorAE2021:~ anthonynm$ gsmartcontrol
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Model Number"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "PCI Vendor/Subsystem ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "IEEE OUI Identifier"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Controller ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "NVMe Version"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Number of Namespaces"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Firmware Updates (0x02)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional Admin Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional NVM Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Maximum Data Transfer Size"
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section(): Unknown section encountered.
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Model Number"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "PCI Vendor/Subsystem ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "IEEE OUI Identifier"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Controller ID"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "NVMe Version"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Number of Namespaces"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Firmware Updates (0x02)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional Admin Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Optional NVM Commands (0x0004)"
<warn>  [app] SmartctlParser::parse_section_info_property(): Unknown property "Maximum Data Transfer Size"
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section_info(): Unknown Info line encountered.
<warn>  [app] SmartctlParser::parse_section(): Unknown section encountered.
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<warn>  [app] SmartctlParser::parse_full(): No ATA sections could be parsed. Returning.
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<warn>  [app] SmartctlParser::parse_full(): No ATA sections could be parsed. Returning.
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<warn>  [app] SmartctlParser::parse_full(): No ATA sections could be parsed. Returning.
<warn>  [hz] Warning: exit: Device open failed, or device did not return an IDENTIFY DEVICE structure.
<warn>  [app] SmartctlParser::parse_full(): No ATA sections could be parsed. Returning.

All of the attached devices display SMART data in Unraid, DriveDX, and Disk Utility

**To Reproduce**
Install and open.

**Comment by ashaduri** [comment]
Duplicate of #4
