### ISSUE TITLE
Arch: Missing dependency pcre

### ISSUE THREAD

**Issue by robschi** [ashaduri/gsmartcontrol#57]
**Version and Environment**
 - GSmartControl version: 1.1.4
 - OS: Arch

**Describe the Bug**
gsmartcontrol can not start with the following error:
`gsmartcontrol: error while loading shared libraries: libpcrecpp.so.0: cannot open shared object file: No such file or directory`

Search for "libpcrecpp.so" reveals:
```
pacman -Ss  libpcrecpp.so
core/pcre 8.45-4
        A deprecated library that implements Perl 5-style regular expressions
```

After installing "pcre" gsmartcontrol can start again, so please add "pcre" as dependency for arch

**Comment by ashaduri** [comment]
Please file this bug report with Arch package maintainers
https://archlinux.org/packages/extra/x86_64/gsmartcontrol/
