### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by cabiamdos** [ashaduri/gsmartcontrol#59]
**Version and Environment**
 - GSmartControl version: [Are you using the latest released version or git?]
 - OS: [e.g. openSUSE Linux 15.4]
gsmartcontrol-1.1.4
kali linux 6.6.9-amd

**Describe the Bug**
[A clear and concise description of what the bug is].
I just downloaded the gsmartcontrol-1.1.4.bz2, there is no installation instructions and when I run the "install-sh"
```
cat INSTALL
See README.txt file, Installation section.
```

```
ls
AUTHORS.txt            LICENSE_gpl2.txt           Makefile.in  autogen.sh            configure.ac         gsmartcontrol.spec
COPYING                LICENSE_gpl3.txt           NEWS         compilation_flags.in  contrib              gsmartcontrol.spec.in
ChangeLog              LICENSE_gsmartcontrol.txt  README.txt   compile               data                 install-sh�����\ɵO�Y�zLuJ  �EINSTALL                LICENSE_hz.txt             TODO         config.guess          debian.dist          missing
LICENSE_boost_1_0.txt  LICENSE_unlicense.txt      aclocal.m4   config.h.in           depcomp              src�af����'��<+`GW[���H[�V^�LICENSE_bsd-ac.txt     LICENSE_zlib.txt           ar-lib       config.sub            file2csource.sh      version.txt.in
LICENSE_bsd-ucb.txt    Makefile.am                autoconf.m4  configure             gsmartcontrol.kdev40�G`U
```
**To Reproduce**
```
wget https://github.com/ashaduri/gsmartcontrol/releases/download/v1.1.4/gsmartcontrol-1.1.4.tar.bz2
install-sh
No input file specified
```

**Screenshots**
[If applicable, add screenshots to help explain your problem].

**Additional Context**
[Add any other context about the problem here (GTK+ version, etc...)]

**Comment by ashaduri** [comment]
The main GitHub page page (README.md) clearly points to the [Downloads](https://gsmartcontrol.shaduri.dev/downloads) page, where you can pick the package for your distribution.
If your Linux distribution is not listed, contact its maintainers for instructions, or compile from source using `./configure && make && make install` (if it's 1.1.x branch).
