### ISSUE TITLE
Need a new stable version.

### ISSUE THREAD

**Issue by antdude** [ashaduri/gsmartcontrol#6]
No new stable version since 2017-11-12! :O

**Comment by ashaduri** [comment]
Which feature do you need from the main branch that is not available in the last released version?

**Comment by antdude** [comment]
Be able to read SSDs' SMART.

**Comment by ashaduri** [comment]
SATA SSDs are supported in the released version.
For NVMe SSD support see #4 .
Either way, no real difference between the main branch and the released version.

**Comment by antdude** [comment]
Thanks.
