### ISSUE TITLE
Crash when saving smartctl output on Windows

### ISSUE THREAD

**Issue by ashaduri** [ashaduri/gsmartcontrol#67]
**Version and Environment**
 - GSmartControl version: 2.0.0
 - OS: Windows 11

**Describe the Bug**
GSmartControl crashes when clicking "Save As" button in Device Information window.
This seems to affect only the Windows package (most likely a GTK+ packaging issue).

**Comment by Chealer** [comment]
I am also affected, on Windows 11 23H2 and also GSmartControl 2.0.0. This occurs with either my SSD (Intel SSD Pro 7600p Series) or my USB flash drive, and whether I activate _Save As_ directly or via _View Output_.

Thank you for creating this ticket @ashaduri. I suggest retitling to something like:

> "Save As" (for smartctl JSON output) crashes on Windows

**Comment by ashaduri** [comment]
Fixed in 2.0.1.

**Comment by Chealer** [comment]
I confirm. Thank you @ashaduri !
