### ISSUE TITLE
Trying to build, cannot find 'format' include

### ISSUE THREAD

**Issue by fallingrock** [ashaduri/gsmartcontrol#70]
**Version and Environment**
 - GSmartControl version: Git
 - OS: Ubuntu 22.04

**Describe the Issue**
Trying to build the latest because Ubuntu provides a 1.xx version.

Get this error:
gsmartcontrol/src/applib/selftest.cpp:19:10: fatal error: format: No such file or directory
   19 | #include <format>
      |          ^~~~~~~~

There is no indication of what dependencies are missing to build the program.

**Comment by ashaduri** [comment]
GCC 13+ is required to build GSmartControl 2.0.x.
CMake should have caught it, but I guess it didn't.

**Comment by fallingrock** [comment]
Got it, thanks.
