### ISSUE TITLE
The Power-On-Time raw value overflows in the Lifetime hours column

### ISSUE THREAD

**Issue by ojsl1** [ashaduri/gsmartcontrol#73]
**Version and Environment**
 - GSmartControl version: 1.1.4
 - OS: Manjaro Linux

**Describe the Bug**
There is an overflow in the `Lifetime hours` column, while the raw value in the Attributes tab for the disk is displayed correctly.

**To Reproduce**
1. Go to Device Information for a disk that has at least more than 65177 hours of lifetime
2. Click on Self-Tests tab
3. Scroll down to Self-Test log

**Screenshots**
![Screenshot_20241225_223947](https://github.com/user-attachments/assets/e8298e9e-3e6f-4618-8c1c-623915fd5a2d)
![Screenshot_20241225_224719](https://github.com/user-attachments/assets/0900d49f-57ce-4a07-a16e-cb40ff8bda9b)

**Additional Context**
gtkmm3: 3.24.9

**Comment by ashaduri** [comment]
Hi,

Unfortunately, this is a defect in ATA specification (?).

Per [smartctl man page](https://linux.die.net/man/8/smartctl): `Note: this time stamp wraps after 2^16 hours, or 2730 days and 16 hours, or about 7.5 years.`

I added the clarification to the header tooltip to avoid further confusion.

Thanks
